@startuml
actor Usuario

usecase "Listar IDs de pedidos" as UC1
usecase "Buscar pedido" as UC2
usecase "Crear pedido mediante formulario" as UC3
usecase "Borrar pedido" as UC4
usecase "Editar pedido (cantidad y descuento)" as UC5
usecase "Guardar pedidos en JSON" as UC6

Usuario -- UC1
Usuario -- UC2
Usuario -- UC3
Usuario -- UC4
Usuario -- UC5

UC3 --> UC6
UC4 --> UC6
UC5 --> UC6
@enduml
